### ISSUE TITLE
Input 0 is incompatible with layer model

### ISSUE THREAD

**Issue by passermyh** [nju-websoft/AliNet#6]
Thanks for your work!
I met this problem:
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    gcn_model.train(args.batch_size, max_epochs=args.max_epoch, start_valid=args.start_valid, eval_freq=args.eval_freq)
  File "/hy-tmp/AliNet/code/alinet.py", line 344, in train
    self.input_embeds, self.output_embeds_list = self.model((self.pos_link_batch, self.neg_link_batch),
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 998, in __call__
    input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/input_spec.py", line 271, in assert_input_compatibility
    raise ValueError('Input ' + str(input_index) +
ValueError: Input 0 is incompatible with layer model: expected shape=(None, 2), found shape=(4500, 3)

What should I do?

**Comment by 2lazy2grow** [comment]
hello, when running this code, I encountered the same problem as you. Can you tell me how you solved this problem?Thank you very much.
